### ISSUE TITLE
I never managed to get it to work

### ISSUE THREAD

**Issue by darkzbaron** [PostLogical/ooler_ble_client#1]
Hi there, it seems that in order to connect you need to press the button on the device which defeats the purpose of automating it away. Any luck on your side?

**Comment by PostLogical** [comment]
I know it's been a long time since you posted this, but I'm not sure I understand your hope. There cannot be an automation that does not get granted access by physically pressing on the device. The key is that you don't have to press it every time, just the first time. This library was created to enable the Home Assistant integration I made that is simply called Ooler. It is best practice to separate out this code into a library that is referenced in the integration. Others could therefore use this library in different contexts, but it certainly works for me using the integration.
